erDiagram
    osm_ways {
        bigint osm_id PK
        geometry geom "WGS84 (4326)"
        geometry geom_3857 "Mercator (3857)"
        jsonb tags "All OSM Tags"
        text highway "Road Type"
        text maxspeed
        int lanes
    }

    osm_cached_tiles {
        text tile_key PK "z-x-y or lon-lat"
        geometry bbox
        timestamp last_download
        text status "pending/done"
    }

    osm_relations {
        bigint transmission_id PK
        bigint member_role
    }

    %% Relationships
    osm_cached_tiles ||--o{ osm_ways : "contains"
    osm_ways }|..|{ osm_relations : "member of"
