flowchart LR
    %% --- Стили ---
    classDef raw fill:#e1f7d5,stroke:#333;
    classDef proc fill:#fff0b3,stroke:#f39c12;
    classDef db fill:#d5e8f7,stroke:#005f9e;

    %% 1. Вход
    BigData[("Большой файл OSM<br/>(Вся область)")]:::raw --> Splitter{Нарезка<br/>на тайлы}
    
    %% 2. Параллельная нарезка
    Splitter --> Chunk1["Тайл №1<br/>(ОЗУ)"]:::proc
    Splitter --> Chunk2["Тайл №2<br/>(ОЗУ)"]:::proc
    Splitter --> ChunkN["Тайл №N<br/>(ОЗУ)"]:::proc
    
    %% 3. Логика (Grid Noding)
    Chunk1 -->|Поиск перекрестков| Node1["Обработ. сегменты"]:::proc
    Chunk2 -->|Поиск перекрестков| Node2["Обработ. сегменты"]:::proc
    ChunkN -->|Поиск перекрестков| NodeN["Обработ. сегменты"]:::proc
    
    %% 4. Сборка
    Node1 --> Merge[("Единая таблица ребер<br/>(graphs.edges)")]:::db
    Node2 --> Merge
    NodeN --> Merge