sequenceDiagram
    participant Py as Python (PyQt5 Backend)
    participant IPC as QWebChannel (Transport)
    participant JS as JavaScript (Frontend)

    Note over Py, JS: Инициализация (Injection)
    %% Добавили регистрацию config, чтобы билось с текстом
    Py->>IPC: registerObject("config", config_bridge)
    Py->>IPC: registerObject("logger", logger_bridge)
    Py->>IPC: registerObject("zoom", zoom_bridge)
    IPC->>JS: Инъекция объекта window.qt
    
    activate JS
    JS->>IPC: new QWebChannel(qt.webChannelTransport)
    IPC-->>JS: Канал готов (Ready)
    deactivate JS

    %% Сценарий 1: Логирование (Data Stream)
    Note over Py, JS: Сценарий 1: Перехват логов
    JS->>JS: console.error("Tile Error")
    JS->>IPC: logger.log("Tile Error")
    IPC->>Py: Вызов слота: log_message(...)
    Py->>Py: Запись в systemd/file

    %% Сценарий 2: Реакция (Event Driven)
    Note over Py, JS: Сценарий 2: Синхронизация LOD
    JS->>JS: map.on('zoomend')
    JS->>IPC: zoom.onZoomChanged(14.5)
    IPC->>Py: Вызов слота: update_zoom(14.5)
    activate Py
    Py->>Py: Пересчет стратегии LOD
    deactivate Py

    %% Сценарий 3: Управление (RPC)
    Note over Py, JS: Сценарий 3: Управление камерой
    Py->>Py: Клик по маршруту
    Py->>JS: runJavaScript("map.flyTo({...})")
    activate JS
    JS->>JS: WebGL Animation
    deactivate JS