sequenceDiagram
    autonumber
    participant C as Клиент
    participant G as Gateway
    participant TE as Traffic Engine (Ядро)
    participant Grid as Spatial Grid
    participant RALT as TD-ALT Router
    participant VM as Volume Manager 

    Note over C, G: 1. Клиент<br>запрашивает маршрут
    C->>G: HTTP POST <br>/routing/calculate {waypoints}
    activate G
    
    Note over G: Упаковка struct.pack<br>(cmd_head + route_head + points)
    
    Note over G, TE: 2. Передача бинарного<br>запроса по ZMQ REQ
    G->>TE: ZMQ REQ <br>(Binary buffer 30b + 5b<br> + float coordinates)
    activate TE
    
    Note over TE, Grid: 3. Привязка географических<br>координат к рёбрам
    TE->>Grid: find_closest_edges<br>(waypoints)
    Grid-->>TE: EdgeID (source),<br>EdgeID (target)
    
    Note over TE, RALT: "4. Инициализация<br> маршрутизатора"
    TE->>RALT: compute_route<br>(source, target)
    activate RALT
    
    loop Процесс релаксации рёбер (ALT)
        RALT->>VM: get_dynamic_weight<br>(edge_id, cur_time)
        Note over VM: Расчет BPR-задержки<br> по плотности трафика
        VM-->>RALT: Dynamic Weight (сек.)
    end
    
    RALT-->>TE: RoutingResult<br> {path_edges, etas,<br> total_weight}
    deactivate RALT
    
    Note over TE: Формирование 5-частного<br> ответа (ZMQ Multi-part)
    
    Note over TE, G: 5. Возврат многочастного<br> ответа ZMQ REP
    TE-->>G: Frame 1: Header <br>(success, edges, points,<br> dist, time, calc_ms)<br>Frame 2: EdgeIDs (uint32[])<br>Frame 3: ETAs (float[])<br>Frame 4: PointCounts (uint16[])<br>Frame 5: GeometryData <br>(float x/y[])
    deactivate TE
    
    Note over G: Распаковка struct.unpack и <br>сборка GeoJSON LineString
    
    G-->>C: "HTTP JSON Response:<br> {status: success, routes: <br>[{segments, dist, time}]}"
    deactivate G
